//GETTERS
export const GET_TODOS = "GET_TODOS"

//MUTATIONS
export const ADD_TODO = "ADD_TODO" 
export const REMOVE_TODO = "REMOVE_TODO"
export const REMOVE_MSG = "REMOVE_MSG"

//ACTIONS
export const ADD_TODO_ACTION = 'ADD_TODO_ACTION'
export const REMOVE_TODO_ACTION = 'REMOVE_TODO_ACTION'
export const REMOVE_MSG_ACTION = 'REMOVE_MSG_ACTION'